vich_uploader:
    db_driver: orm

    mappings:
      livre:
           uri_prefix: /images/livre
           upload_destination: '%kernel.project_dir%/public/images/products'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
